### ISSUE TITLE
Is the anononymous account needed?

### ISSUE THREAD

**Issue by shochdoerfer** [passbolt/passbolt#7]
I realized that an anonymous user account was created in the database. What is the reasoning behind this? It looks a bit wired for a sofware claiming to be respectful of privacy to have such account in place. Maybe I missed a bit in the documentation but I did not realize that such an accounts exists.

**Comment by shochdoerfer** [comment]
I just deleted the account in our set-up, does this have any negative side-effects?

**Comment by stripthis** [comment]
This is used by the system mostly for creating a user context (see. User::get) when we do not know the identity of the user, for example to log errors, find out what the current role is, etc. Since the user role of this anonymous user is guest it cannot access anything but the login page or registration page. It cannot login or access any data like a regular user.

I wouldn't recommend deleting it for now.
